#!/usr/bin/env bash
# Install Nginx web server and configure it
# Print 'Hello World!'

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
