#!/usr/bin/env bash
# Install Haproxy to configure two servers to be load-balanced

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

echo "
listen load_balancer
   bind 0.0.0.0:80
   mode http
   stats enable
   stats uri /haproxy?stats
   balance roundrobin
   option httpclose
   option forwardfor
   server 83934-web-01 100.25.205.123:80 check
   server 83934-web-02 100.25.47.49:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
