#!/usr/bin/env bash
# Fizzbuzz program from 1-100

i=1
while [ "$i" -le 100 ]
do
  if ! (("$i" % 15))
  then
    echo 'FizzBuzz'
  elif ! (("$i" % 5))
  then
    echo 'Buzz'
  elif ! (("$i" % 3))
  then
    echo 'Fizz'
  else
    echo "$i"
  fi
(( i++ ))
done
