#!/usr/bin/env bash
# tTell the story of passwd

file="/etc/passwd"

while IFS=':' read -r user password uid gid uidinfo home shell
do
  echo "The user $user is part of the $gid gang, lives in $home and rides $shell."\
	"$uid's place is protected by the passcode $password,"\
	"more info about the user here: $uidinfo"
done < "$file"
