#!/usr/bin/env bash
# Display numbers 1-20 with info on superstitions

i=1
while [ "$i" -le 20 ]
do
  if (( "$i"==17 ))
  then
    echo "$i"
    echo 'bad luck from Italy'
  elif (( "$i"==9 ))
  then
    echo "$i"
    echo 'bad luck from Japan'
  elif (( "$i"==4 ))
  then
    echo "$i"
    echo 'bad luck from China'
  else
    echo "$i"
  fi
  (( i++ ))
done
